const Footer = () => {
    return (
        <>
            <div className="footer">
                We are not an offer or solicitation to lend. The website only provides a service and is not an agent, representative, or broker of any lender and does not endorse or charge you for any loan or product. The website operators are not lenders, do not make loans of any type, and do not make credit decisions. The website collects personal information provided by you and forwards it to partners in our lender network and third-party networks of lenders. You are under no obligation to use this website or service to initiate, contact, nor apply for credit or any loan product with any service provider or lender. Loan amounts vary from $100 and $50,000 but not all lenders can provide up to $35,000. Providing your information on the website does not guarantee you will be approved for a loan or credit product. Cash transfer times may vary between lenders and may depend on your individual financial institution. In some circumstances faxing may be required. Any of the above referenced suggestions are based on industry best practices and should be used for informational purposes only and not construed as legal advice. You should contact your attorney to obtain advice with respect to any particular issue or problem. Short-term cash loans are meant to provide you with short-term financing to solve immediate cash needs and should not be considered a long-term solution. This service and lenders are not available in all states. Lenders may perform credit checks with the three credit reporting bureaus: Experian, Equifax, or Trans Union or may perform alternative credit checks or consumer reports through alternative providers. By submitting your request, you acknowledge, agree, and authorize that (a) your information may be sent to lenders and/or third-party partners on your behalf, and (b) such lenders may obtain consumer reports and related information about you from one or more consumer reporting agencies, such as TransUnion, Experian and Equifax to evaluate your creditworthiness. Important : We do not sell your personal data...<a href="#">Read More</a>
            </div>
        </>
    )
}

export default Footer;